name: Simple CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build backend
        working-directory: backend
        run: echo "✅ Backend build passed!"

      - name: Build frontend
        working-directory: frontend
        run: echo "✅ Frontend build passed!"